list = 'LA CORRIENTE O TENSION QUE EXISTE EN CUALQUIER ELEMENTO DE UNA RED LINEAL BILATERAL ES IGUAL A LA SUMA ALGEBRAICA DE LAS CORRIENTES O LAS TENSIONES PRODUCIDAS INDEPENDIENTEMENTE PARA CADA FUENTE'
print(list)
y = list.split('O')
print(y)
x = ','.join(map(str, y))
print(x)